spring.application.name=DevShowcase

server.port=${PORT:8080}

spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5432/devshowcase}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
